### ISSUE TITLE
Have just a catalog of zones and no properties

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#2]
The draft in it's current state already does not have properties, but we might want to remove all RR-types describing the types of potential future properties.

**Comment by wtoorop** [comment]
Properties could be configured in implementation specific templates, and slaves could have multiple template/catalog zone combinations.

**Comment by libor-peltan-cznic** [comment]
In any case I would enable implementation-specific stuff in catalog zone (possibly configuration options). The draft might just mention that: "All the records in catalog zone, that are not understood by the implementation, SHOULD be ignored." (or something like this)

**Comment by wtoorop** [comment]
resolved cause PR merged
