### ISSUE TITLE
Zones need to reset state if their <unique-id> changes

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#3]
It is impossible to reliably track deletion / addition for zones, because secondaries might miss notifies or they might be down.

Having the ability to reset the state of a secondary zone is important in situations like when a zone ownership is changed. In that case you do not want the new owner to inherit the metadata.
Other situations might be resetting DNSSEC state...

**Comment by Habbie** [comment]
This also means that masters should promise to change the ID if a domain was removed&added again.

**Comment by libor-peltan-cznic** [comment]
The only alternative seems to be that the secondaries will promise to never go down for long enough :)

**Comment by wtoorop** [comment]
Resolver by PR #7
