### ISSUE TITLE
<unique-N> IDs may be predictable

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#30]
Which we should mention in the document that some implementations may have that (especially since we abandoned zone state reset by ID change).
And in several places in the document what that would entail in that context.

**Comment by peterthomassen** [comment]
> This has consequences for so many things in the document, that I think it should be described in a follow-up document. We can than also settle on what hash to use etc. Support for it can then be signaled in the Schema property (which allows for more than one RR to support backwards compatibility). @peterthomassen What do you think?

Doing this in another document means this is out of scope for the current document, so the issue should be closed.
