### ISSUE TITLE
Add (minimal) text about expiry of catalog zones

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#35]
what shall happen when a catalog zone expires?
1) Catalog zone shall never expire
2) Member zones shall be expired
3) Member zones shall be purged with their metadata
4) .... ?

**Comment by libor-peltan-cznic** [comment]
I agree. Btw, current behaviour of Knot DNS: when interpreted catalog zone expires, it expires as a normal zone (log message, stops answering queries to the catalog zone itself), but it does nothing with its member zones: they are still configured based on persistent catalogDB, with the reference to the expired (but still configured) catalog zone. Even after server re-boot.

I guess we can leave to the implementation, if the (debug) queries to interpreted catalog zone are working after its expiry or not.

I assume we need to clarify this somehow in our draft, and revise all mentions of "expir[a-z]*" there.
