### ISSUE TITLE
Clarify behavior when MUST condition is violated

### ISSUE THREAD

**Issue by pspacek** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#39]
Please clarify what consumer should do when MUST/MUST NOT conditions are violated.

For example:
> This PTR record MUST be the only record in the PTR RRset with the same name.
More than one record in the RRset denotes a broken catalog zone which MUST NOT be processed (see (#generalrequirements)).

Does this mean that:
- Whole catalog zone update is ignored? (= whole content of IXFR is ignored?)
- Update for the single zone is ignored and rest of the zone is processed?
- Only first PTR is processed (I hope not)? What if the order PTRs changes of on next AXFR?

Similarly for other MUSTs.

Motivation: It helps with interoperability in the long term. If it is not clearly specified implementations might decide to treat it differently and _then_ users are asking weird questions like "implementation A is wrong because implementation B can handle this" etc.

**Comment by pspacek** [comment]
Additional place where a clarification would help>
> The producer MUST NOT assign more than one `group` property to one member zone.

If this is violated, then...? Ignore the group but install the zone? Or ignore the zone? What if the zone is already present and second group property is added? Keep the previous config? Or remove the zone? What if we keep the previous config, is it expected to persist between restarts (when catalog zone retrasfer will have double-group immediately on catalog zone load?)

**Comment by wtoorop** [comment]
In commit c250a2f I have added some text for the two cases you mentioned. The first case in section General Requirements (to which it refers), and the second case in the section on the group property. I've scanned the text for more cases, but those were the only ones.

**Comment by wtoorop** [comment]
Fixed in PR #45
