### ISSUE TITLE
Clarify text about ordering of operations for Change of Ownership (`coo` property)

### ISSUE THREAD

**Issue by pspacek** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#40]
Text in the draft:

> When a consumer of catalog zone `$NEWCATZ` receives an update of `$NEWCATZ` which adds or changes a member zone, *and* that consumer had the member zone associated with `$OLDCATZ`, *and* there is a `coo` property of the member zone in `$OLDCATZ` pointing to `$NEWCATZ`, *only then* it will reconfigure the member zone with the for `$NEWCATZ` preconfigured settings.

Would it be possible to somehow rephrase it? It is hard to read as it is one gigantic sentence and at the same time it is not obvious from the text why the ordering must be exactly this.

Question from a new draft reader: Why the transfer should not happen if the zone is first added to the new catalog and only the the `coo` property is added to later? (Or the transfer of the first zone is delayed, e.g. because of lost notify?) At least once sentence to the effect of "because it allows stateless implementation" would help.

**Comment by wtoorop** [comment]
This was resolved in 83a96e5
