### ISSUE TITLE
Operational note: notifies for not-yet-existing zones

### ISSUE THREAD

**Issue by pspacek** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#41]
This is just a note, probably not worth mentioning in the text. I just wanted to capture the knowledge somewhere.

The current behavior might cause primaries to send notifies to secondaries _before_ the zone is processed on secondaries. This might cause floods of log messages like this:

```
named[60513]: client @0x7fb5740345b8 172.31.47.136#34372: received notify for zone 'zone150.zones.cat': not authoritative
```
(comes from BIND 9.18.1)

**Comment by wtoorop** [comment]
Yeah... maybe under a new section "Operation notes"? Postponing resolving this into text until I come up with a good spot to cover this.

**Comment by wtoorop** [comment]
Turns out our "Implementation notes" contained already some operational notes, so I renamed it. We can add this there too.

**Comment by wtoorop** [comment]
fixed
