### ISSUE TITLE
Warn about property name clashes

### ISSUE THREAD

**Issue by pspacek** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#42]
I think it would be good to add a note about potential name clashes between custom properties and _future_ global properties.

Something like:
"Implementations SHOULD namespace their custom properties to limit risk of clashes with future versions of catalog zones and standardized extensions. An example namespaced property might be named `serial-nsd` or something similar."

**Comment by wtoorop** [comment]
Fixed in commit de5e007 in PR #45
