### ISSUE TITLE
Add some recommendation for naming catalog zones

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#46]
@Jakker pointed out to me that he saw examples of catalog zones in the wild hijacking a tld.
I guess we can add some text suggesting to either use a domain you own, or use a suitable special use domain name (SUN).
Question is, which SUN! .internal would have been ideal (see: https://datatracker.ietf.org/doc/draft-wkumari-dnsop-internal/ )
Now we'd have to do with .test. or .example. or .home.arpa. or something... should we try to register catz.arpa as SUN for this?

**Comment by peterthomassen** [comment]
Does someone have a pointer why the `.internal` draft did not continue? (I'm wondering if it's worth reviving it?)

**Comment by wtoorop** [comment]
@peterthomassen There is an issue on the github repo w.r.t. to this: https://github.com/wkumari/draft-wkumari-dnsop-internal/issues/6
It looks like it is currently common to register a SUN under .arpa. nowadays... 
See the recent: 6tisch.arpa., eap-noob.arpa. and home.arpa. in https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml
