### ISSUE TITLE
IANA registry for group property values

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#58]
Requested by Murray Kucherawy and Paul Wouters

**Comment by wtoorop** [comment]
@letoams:
It seems like Section 4.4.2 defines "group properties" that are standardized, while Section 4.5 specifies Private Use group properties. But there is actually no registry created for Group Properties, and no definitions other than "examples" are given. This makes the status of, for example "nodnssec", unclear. Is this a custom (eg bind implementation only) property or is this really a custom private use entry, in which case the example is bad as it belongs under .bind.ext.

Since "nodnssec" seems a real use case, why does this document not create an IANA registry for Catalog Zone Group Properties and places "nodnssec" in it?

**Comment by wtoorop** [comment]
@Habbie suggests to move the group property out of the draft all together and create a new draft for it. I think that would be reasonable since we currently have only one implementation for it. @libor-peltan-cznic what do you think?

**Comment by wtoorop** [comment]
Copying co-author consensus from the [catalog-zones Mattermost channel](https://chat.dns-oarc.net/community/channels/catalog-zones):

What the group values mean is determined by the consumer of that specific catalog. We don't assume coordination of consumers. If a producer publishes its zones (via a catalog) with multiple consumers, it may as well produce multiple catalogs for the different consumers.

In any case, as stated by @mind04 , there are no group properties, only group property values.

**Comment by wtoorop** [comment]
> @letoams writes:
> 

Dear Paul, Warren and Murray,

> ### Group Properties
> It seems like Section 4.4.2 defines "group properties" that are standardized, while Section 4.5 specifies Private Use group properties.

This is a misunderstanding. There are no "group properties", only "group property values". The values listen in 4.4.2 are only examples and not standardized.
The confusion probably stems from the sentence: `Consumer operators SHOULD namespace their group properties to limit risk of clashes.` Commit 1ab59dba fixes this by changing that into: `Consumer operators SHOULD namespace their group property values to limit risk of clashes.`.

Section 4.5 is about Custom properties and not about group property values. The authors do see that there maybe value in a registry for property values and are creating and discussing text for it. 

Catalog consumer operators have specific configuration associated with their catalog zone. For example from which primary to transfer the member zones. The group property is meant to provide alternative configuration within that catalog. Alternatively the consumer and producer could have multiple catalogs, each with different configuration associated, and the member could be moved from one catalog to the other.

There is no need for a registry for common names used for the catalog zones themselves. Similarly specific values for the group property don't need to be specified. The catalog producer can tell the consumer operator how it wants the different group property values to be associated with different configuration for their relationship. If that is really not possible (but I cannot see how it could not be) than the producer and consumer can always setup a new catalog zone for the desired configuration with that consumer operator.

> But there is actually no registry created for Group Properties, and no definitions other than "examples" are given. This makes the status of, for example "nodnssec", unclear. Is this a custom (eg bind implementation only) property or is this really a custom private use entry, in which case the example is bad as it belongs under .bind.ext.
> 
> Since "nodnssec" seems a real use case, why does this document not create an IANA registry for Catalog Zone Group Properties and places "nodnssec" in it?

**Comment by letoams** [comment]
On Mon, 30 Jan 2023, Kees Monshouwer wrote:

> A registry makes imho no sense for what are basically random local values which are agreed upfront by
> the producer and consumer operator.

I disagree. Because it seems to be used already by implementations to
convey "options". So if I replace my DNS server of vendor A with one
from vendor B, there will be a change in operation unless these kind
of options are standardized.

The "do not sign with DNSSEC" is the first such option that appears
useful (and in use already!).

Paul

**Comment by Habbie** [comment]
Those "options" match templates, written by operators, that happen to have descriptive names. It might be better to use non-descriptive examples in the draft to avoid this exact confusion.

**Comment by letoams** [comment]
On Mon, 30 Jan 2023, Peter van Dijk wrote:

> Those "options" match templates, written by operators, that happen to have descriptive names. It
> might be better to use non-descriptive examples in the draft to avoid this exact confusion.

I don't think it matters whether you call them options or templates. If
there is a set of information that needs to be communicated, it should
be done within the protocol and not via a private non-interoperable
method.

**Comment by Habbie** [comment]
It matters what you call them, because of what they are. They are not globally defined options. They are agreed-upon groups. We could also have called them tags, might have been clearer?

**Comment by letoams** [comment]
On Mon, 30 Jan 2023, Peter van Dijk wrote:

> It matters what you call them, because of what they are. They are not globally defined options. They
> are agreed-upon groups. We could also have called them tags, might have been clearer?

Call them what you want, just create an IANA registry for them and carve
out a bit for private use :)

**Comment by Habbie** [comment]
You're asking for something fundamentally different - something that perhaps could be done in a followup document.

**Comment by mind04** [comment]
> Call them what you want, just create an IANA registry for them and carve out a bit for private use :)

Creating a registry is no goal by itself.... A registry for template names makes no sense no matter how you look at it.

**Comment by letoams** [comment]
On Mon, 30 Jan 2023, Kees Monshouwer wrote:

>       Call them what you want, just create an IANA registry for them and carve out a bit for
>       private use :)
> 
> Creating a registry is no goal by itself.... A registry for template names makes no sense no matter
> how you look at it.

Ok, seems we are going in circles, so I'll take a step back.

Paul

**Comment by wtoorop** [comment]
@paulwouters

We (the draft co-authors) have discussed how to best convey the scope of the meaning of group values extensively, which eventually resulted in the merge of PR #65 .

The group properties now have non-descriptive names as to not suggest that they have meanings in implementations (*what* they "mean" is namely determined and configured by the consumer operator).
And we have extended the lines about catalog producers publishing at two consumer operators and how mapping of group values is a matter of those producer/consumer relationships:

> Implementations MAY facilitate mapping of a specific group value to specific configuration configurable on a per catalog zone basis to allow for producers that publish their catalog zone at multiple consumer operators. Consumer operators SHOULD namespace their `group` values to reduce the risk of having to resolve clashes.

**Comment by wtoorop** [comment]
Reply sent
