### ISSUE TITLE
Section 4.3.1 Versioning

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#59]
What should one do if the version supported is lower than the version of zone received? Attempt to understand it? preventively fail?

Are version 1 and 2 compatible? In what ways are they not? Should perhaps version 1 catalog zones always be ignored ?

**Comment by wtoorop** [comment]
@paulwouters

Version 1 and 2 are not compatible. Version 1 was bind's original but not standardized idea/implementation.
New implementations are better of implementing version 2 because the exact details of version 1 are not standardized (and thus kind of unknown)
However, besides BIND, PowerDNS does have an implementation of consumption of version 1 catalog zones.

Does that answer your question?

**Comment by Habbie** [comment]
(please note that the powerdns v1 consumer is not what we ship in powerdns today. We ship the v2 producer and consumer. The v1 consumer was an experiment that we should ignore now.)

**Comment by paulwouters** [comment]
It answers my question, but this answer should be in the draft too. Even if it is just to say "v1 was an experimental protocol and SHOULD NOT be supported" or "when receiving a v1, one SHOULD return XXX error"

**Comment by mind04** [comment]
What is unclear about this?
```
Catalog consumers MUST NOT apply catalog zone processing to.

  - zones without the `version` property
  - zones with a `version` property with more than one RR in the RRset
  - zones with a `version` property without an expected value in the
    `version.$CATZ` TXT RR

These conditions signify a broken catalog zone which MUST NOT be processed (see
(#generalrequirements)).
```

**Comment by wtoorop** [comment]
> It answers my question, but this answer should be in the draft too. Even if it is just to say "v1 was an experimental protocol and SHOULD NOT be supported"

We cannot say that because, v1 catalog zones have been (and probably still are) in production in BIND only deployments.

> or "when receiving a v1, one SHOULD return XXX error"

This is indeed not in the text explicitly. "zones with a `version` property without an expected value in the `version.$CATZ` TXT RR" is not explicit enough. I'll make a more explicit line.

**Comment by wtoorop** [comment]
Commit 8eed29f9 adds the explicit mention that version 1 catalog zones should also be considered broken by catalog consumers that only have version 2 implemented.
@paulwouters Is that explicit enough?

**Comment by paulwouters** [comment]
yes that is fine

**Comment by wtoorop** [comment]
Reply sent
