### ISSUE TITLE
5.3 "MUST be removed"?

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#60]
```
        Only when the zone was configured from a specific catalog zone,
        and the zone is removed as a member from that specific catalog
        zone, the zone and associated state (such as zone data and DNSSEC
        keys) MUST be removed.
```

What is "removed" here? I think perhaps it should be limited to "MUST no longer be served". For example, it would be bad if the operator made an error, and ended up briefly removing the zone and "removing" (aka destroying) some private DNSSEC keys, complicating the zone restoration. Also, perhaps the implementation wants to simply keep the state on disk but move it to a /var/lib/xxx/zones/archived/ directory. The use of "remove" sounds like that might not be allowed.

**Comment by wtoorop** [comment]
@paulwouters 

Ack! Addresses in commit fdd8d79b by changing the text to:
```
Only when the zone was configured from a specific catalog zone, and the zone is removed as a member from that specific catalog zone, the zone MUST no longer be served.
Any associated state (such as zone data and DNSSEC keys) MUST not be reused for a zone with the same name automatically, though may be archived for mistake recovery purposes.
```

Is that better?

**Comment by mind04** [comment]
Just replace "an authoritative server" by "consumer" in the first sentence and add "from the consumer" to the second one.
```
When a member zone is removed from a specific catalog zone, a consumer MUST NOT remove the zone and associated state data if the zone was not configured from that specific catalog zone.
Only when the zone was configured from a specific catalog zone, and the zone is removed as a member from that specific catalog zone, the zone and associated state (such as zone data and DNSSEC keys) MUST be removed from the consumer.
```
The whole reason catalog zone exists is zone removal from a secondary server (now consumer).

**Comment by wtoorop** [comment]
> Just replace "an authoritative server" by "consumer" in the first sentence and add "from the consumer" to the second one.

That's a good suggestion too! I'll do that, but leave the rest of the suggestion to deal with @paulwouter 's review feedback.

**Comment by wtoorop** [comment]
> > Just replace "an authoritative server" by "consumer" in the first sentence and add "from the consumer" to the second one.
> 
> That's a good suggestion too! I'll do that, but leave the rest of the suggestion to deal with @paulwouters ' review feedback.

Actually, with commit  fd6af64b I've taken @mind04 's suggestion completely and just added a line about mistake recovery so that the whole paragraph is now:

```
   When a member zone is removed from a specific catalog zone, a
   consumer MUST NOT remove the zone and associated state data if the
   zone was not configured from that specific catalog zone.  Only when
   the zone was configured from a specific catalog zone, and the zone is
   removed as a member from that specific catalog zone, the zone and
   associated state (such as zone data and DNSSEC keys) MUST be removed
   from the consumer.  The associated state (such as zone data and
   DNSSEC keys) may be archived before removal for mistake recovery
   purposes.
```

**Comment by mind04** [comment]
I don't like the last line about the mistake recovery as it will give secondary operators a permit to store sensitive information against the will of the producer operator.

**Comment by wtoorop** [comment]
> I don't like the last line about the mistake recovery as it will give secondary operators a permit to store sensitive information against the will of the producer operator.

How about this as last sentence then, to still address Paul's review comment:

```
Consumer operators may consider to temporarily archive associated
state to facilitate mistake recovery, but should not do this for longer
than is strictly necessary for that purpose.
```

**Comment by paulwouters** [comment]
looks good to me. One could add "for a limited time only (eg one week)" if you are afraid of secondaries permanently storing it based on this advise

**Comment by mind04** [comment]
I'm pretty sure consumer and producer operators can figure this out without the guidance of a draft/rfc.

**Comment by wtoorop** [comment]
> looks good to me. One could add "for a limited time only (eg one week)" if you are afraid of secondaries permanently storing it based on this advise

Thanks! Taken along the suggestion in 511041cd . I'll communicate to the proper channels when all this is done and settled between the authors too. Closing for now (to see the milestone progress ;)
