### ISSUE TITLE
Operational Considerations

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#61]
What are the risks and benefits of Extension group properties?

Should one try to standardize these instead? Why is this document not doing that based on its operational experience with eg bind and knot and powerdns ?

**Comment by wtoorop** [comment]
For starters, currently only knot has the group extension

**Comment by wtoorop** [comment]
Hi @paulwouters

> What are the risks and benefits of Extension group properties?
> Should one try to standardize these instead? Why is this document not doing that based on its operational experience with eg bind and knot and powerdns ?

There are no extension group properties. There are properties, of which the document standardizes three already: `version`, `coo` and `group`. Implementations can extend them for their own implementation with custom properties (below the ext label). Bind9 has several custom properties (`primaries`, `allow-query` and `allow-transfer`), but the other implementations don't have them yet. I guess that once the other implementations have similar custom properties (from operator feedback) they can be standardized. But then they are no longer custom properties, but regular properties.

Does this answer your question?

**Comment by paulwouters** [comment]
It answers my question, but if one is experimenting with further properties in the extension part, will these ever move to the standard part? or will non-standard extensions become a defacto standard? But I guess these could end up in a separate followup document.

**Comment by wtoorop** [comment]
> It answers my question, but if one is experimenting with further properties in the extension part, will these ever move to the standard part? or will non-standard extensions become a defacto standard? But I guess these could end up in a separate followup document.

Custom properties will remain in the specific implementation that claimed them initially for backwards compatibility, but if more that one implementation define a similar custom property, they can be standardized via RFC or via a lower barrier procedure.

**Comment by wtoorop** [comment]
Reply sent
