### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#62]
Dealing with high value domains eg [gmail.com](https://gmail.com/) is missing. If a large DNS hoster would enable catalog zones for its customers, how can it prevent rogue takeovers? If fully automated, it can never be safely deployed. If each zone needs a manual check, well than we don't really have "catalog zones" auto-populating name servers.

Is there an expectation that nameservers can do some authorization call before adding a new domain that is already delegated elsewhere? Eg if GoDaddy uses catalog zones, and I am their tiny customer with "[nohats.ca](https://nohats.ca/)" and then add a new zone "[gmail.com](https://gmail.com/)", that could cause a significant disruption. Especially if the malicious person would create another domain that depends on "[gmail.com](https://gmail.com/)" in such a way that GoDaddy's servers will start sending "[gmail.com](https://gmail.com/)" data in their additional data reply for other domains. The section only has a "consumer(s) MAY <do custom smart things>", which in my opinion, is far too weak as a security control. As the above example shows, it is just too easy to start poisoning nameservers via implementations that skip this one MAY clause in the Security Considerations.

**Comment by wtoorop** [comment]
@paulwouters : I've changed the MAY to SHOULD to turn it into a stronger recommendation. Is that sufficiently strong?
```
To prevent unintended provisioning of zones, consumer(s) SHOULD scope the set of
admissible member zones by any means deemed suitable (such as statically, via
regular expressions, or dynamically, by verifying against another database
before accepting a member zone).
```

**Comment by mind04** [comment]
I can definitely live wit MAY and declaring the rest out of scope. MAY is sufficient, as it allows operators to validate before accepting a member zone, no matter in what environment (trusted, hostile) they operate. On the other hand, SHOULD feels a bit strong for a trusted environment and is not adding much value over MAY.

**Comment by wtoorop** [comment]
Reply sent
