### ISSUE TITLE
Appendix A

### ISSUE THREAD

**Issue by wtoorop** [NLnetLabs/draft-toorop-dnsop-dns-catalog-zones#63]
The appendix implementation status only mentions version 2 for bind. Presumably, the other implementations never supported version 1, but this could be made more clear (although granted, it is a little weird so late in the process to do this as it will get cut out before publication anyway, but if a new draft is done based on IESG review comments, please also clarify this.

**Comment by wtoorop** [comment]
TODO:
- [ ] email @letoams about the update

**Comment by letoams** [comment]
On Jan 25, 2023, at 10:58, Willem Toorop ***@***.***> wrote:
TODO:

 email @letoams about the updateSmarty pants! Adding the todo causes this email to happen 😜Changes look good.Paul

**Comment by wtoorop** [comment]
Reply sent
